<?php
namespace Admin\Controller;
use Common\Controller\AdminbaseController;
class DownloadController extends AdminbaseController{
	
	function _initialize() {
		parent::_initialize();
	}
	
	function downExcel()
	{
		
		vendor('PHPExcel.PHPExcel');
		$objExcel=new \ PHPExcel();
		$objWriter = new \PHPExcel_Writer_Excel5($objExcel); 
		// $objWriter = new \PHPExcel_Writer_Excel2007($objExcel);
		$PHPExcel_Style_Alignment = new \PHPExcel_Style_Alignment(); 
		//设置文档基本属性 
	   $objProps = $objExcel->getProperties(); 
	   $objProps->setCreator(" Zhang"); 
	   $objProps->setLastModifiedBy(" Zhang"); 
	   $objProps->setTitle("Office XLS Test Document"); 
	   $objProps->setSubject("Office XLS Test Document"); 
	   $objProps->setDescription("Test document, generated by PHPExcel."); 
	   $objProps->setKeywords("office excel PHPExcel"); 
	   $objProps->setCategory("export"); 
	   //设置当前的sheet索引，用于后续的内容操作。 
	//一般只有在使用多个sheet的时候才需要显示调用。 
	//缺省情况下，PHPExcel会自动创建第一个sheet被设置SheetIndex=0 
	   $objExcel->setActiveSheetIndex(0); 

	    $objActSheet = $objExcel->getActiveSheet(); 
	    $mod=$_GET['mod'];
	    switch($mod){
			    	case "member":
			    	//筛选条件
			    	$file_name="会员导出";
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);
			    	$search_type=trim($_GET['search_type']);
			    	$keyword=trim($_GET['keyword']);
			    	//用户名
			    	if($keyword){
			    		if($search_type=='1')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['name']=array('like',$word);
				    	}
			    	//用户id
				    	if($search_type=='2')
				    	{	
				    		$where['member_id']=$keyword;
				    	}
			    	//手机号
				    	if($search_type=='3')
				    	{	
				    		$word=$keyword."%";
				    		$where['mobile']=array('like',$word);
				    	}
			    	}
			    	if($_GET['sex'])
			    	$where['sex']=trim($_GET['sex']);
			    	if($_GET['grade'])
			    	$where['type']=trim($_GET['grade']);
			    	if($_GET['wx'])
			    	$where['open_id']=array('gt','0');
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where[$time_type]=array('between',array($start_time,$end_time));
			    	
			    	// $where[$time_type]=array('lt',$end_time);

			    	 // print_r($where);die;
			    	$member=M('member');
			    	$member_enrol=M('member_enrol');
			    		$objActSheet->setTitle('优试会员'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"会员数据导出"); 
			    		$objActSheet->mergeCells('A1:O1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','姓名');
			    		$objActSheet->setCellValue('B2','性别');
					    $objActSheet->setCellValue('C2','年龄');
					    $objActSheet->setCellValue('D2','手机号');
					    $objActSheet->setCellValue('E2','所在地');
					    $objActSheet->setCellValue('F2','推荐人');
					    $objActSheet->setCellValue('G2','等级');
					    $objActSheet->setCellValue('H2','信息完整度');
						$objActSheet->setCellValue('I2','积分');
						$objActSheet->setCellValue('J2','注册时间');
						$objActSheet->setCellValue('K2','微信open_id');
						$objActSheet->setCellValue('L2','报名次数');
						$objActSheet->setCellValue('M2','报名成功次数');
						$objActSheet->setCellValue('N2','参与次数');
						$objActSheet->setCellValue('O2','参与完成次数');
					    $objStyleA1 = $objActSheet->getStyle('A2:O2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);
						$objActSheet->getColumnDimension('I')->setWidth(10);
						$objActSheet->getColumnDimension('J')->setWidth(15);
						$objActSheet->getColumnDimension('K')->setWidth(20);
						$objActSheet->getColumnDimension('L')->setWidth(10);
						$objActSheet->getColumnDimension('M')->setWidth(10);
						$objActSheet->getColumnDimension('N')->setWidth(10);
						$objActSheet->getColumnDimension('O')->setWidth(10);
						
					  	$index = 3;
					  	$lists = $member->where($where)->select();
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,$v['name']);
				    		$objActSheet->setCellValue('B'.$index,$v['sex']);
						    $objActSheet->setCellValue('C'.$index,$age);
						    $objActSheet->setCellValue('D'.$index,$v['mobile']);
						    $objActSheet->setCellValue('E'.$index,$v['area_name']);
						    //推荐人
						    if($v['yaoqing'])
						    {
						    	$v_name=$member->field('name')->where("member_id=$v[yaoqing]")->find();
						    	$v['yaoqing']=$v_name['name'];
						    }else{
						    	$v['yaoqing']='无';
						    }
						     $objActSheet->setCellValue('F'.$index,$v['yaoqing']);//推荐人
						     if($v['type']=='1')
						     {
						     	$v['type']='普通';
						     }
						     elseif($v['type']=='2')
						     {
						     	$v['type']='会员';
						     }else{
						     	$v['type']='普通';
						     }
						     $objActSheet->setCellValue('G'.$index,$v['type']);//等级
							$objActSheet->setCellValue('H'.$index,$v['wanzhengdu']);//完整度
							$objActSheet->setCellValue('I'.$index,$v['integral']);// 积分
							$objActSheet->setCellValue('J'.$index,date('Y-m-d H:i',$v['add_time']));//注册时间
							$objActSheet->setCellValue('K'.$index,$v['open_id']);//微信open_id
							//报名次数，报名成功次数  参与次数 完成次数
								$baoming=$member_enrol->where("member_id=$v[member_id]")->count();
								$baoming_success=$member_enrol->where("member_id=$v[member_id] AND baoming=1")->count();
								$canyu=$member_enrol->where("member_id=$v[member_id] AND baoming=1 AND enrol_start_time >0 ")->count();
								$canyu_success=$member_enrol->where("member_id=$v[member_id] AND baoming=1 AND enrol_end_time >0 ")->count();

						    $objActSheet->setCellValue('L'.$index,$baoming);
						    $objActSheet->setCellValue('M'.$index,$baoming_success);
							$objActSheet->setCellValue('N'.$index,$canyu);
							 $objActSheet->setCellValue('O'.$index,$canyu_success);
							// if($nindex!=$index)
							// {
							// 	$index = $nindex;
							// }
							// else
							// {
							// 	WHILE($ARR){

							// 		$index++;
							// 	}
								$index++;
							// }
							

					  	}
			    		break;

			  case "project":
			    	//筛选条件
			    	$file_name="项目导出";
			    	$where['type']=$_GET['type'];
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);
			    	$search_type=trim($_GET['search_type']);
			    	$keyword=trim($_GET['keyword']);
			    	//项目编号
			    	if($keyword){
			    		if($search_type=='1')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['project_no']=array('like',$word);
				    	}
			    		//项目名称
				    	if($search_type=='2')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['title']=array('like',$word);
				    	}
			    		//项目id
				    	if($search_type=='3')
				    	{	
				    		
				    		$where['id']=$keyword;
				    	}
				    	//负责人
				    	if($search_type=='4')
				    	{	
				    		$word=$keyword."%";
				    		$where['user_name']=array('like',$word);
				    	}				    	
			    	}
			    	if($_GET['search_class'])
			    	$where['class']=trim($_GET['search_class']);
			    	if($_GET['search_project_status'])
				    	{	//待审核
				    		if($_GET['search_project_status']=='wait')
				    		{
				    			$where['project_status']=array('neq','1');
				    		}else{
				    			$where['project_status']=array('eq','1');
				    		}
				    	}
				    	
			    	if($_GET['search_project_state'])
			    	$where['state']=trim($_GET['search_project_state']);
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where[$time_type]=array('between',array($start_time,$end_time));
			    	
			    	// $where[$time_type]=array('lt',$end_time);

			    	  // print_r($where);die;
			    	$project=M('project');
			    	$member_enrol=M('member_enrol');
			    		$objActSheet->setTitle('优试项目'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"项目数据导出"); 
			    		$objActSheet->mergeCells('A1:R1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','项目编号');
			    		$objActSheet->setCellValue('B2','项目名称');
					    $objActSheet->setCellValue('C2','项目分类');
					    $objActSheet->setCellValue('D2','隶属客户');
					    $objActSheet->setCellValue('E2','对外发布');
					    $objActSheet->setCellValue('F2','负责人');
					    $objActSheet->setCellValue('G2','创建人');
					    $objActSheet->setCellValue('H2','招募开始');
						$objActSheet->setCellValue('I2','招募结束');
						$objActSheet->setCellValue('J2','项目开始');
						$objActSheet->setCellValue('K2','项目结束');
						$objActSheet->setCellValue('L2','感谢金');
						$objActSheet->setCellValue('M2','积分');
						$objActSheet->setCellValue('N2','通过/报名人数');
						$objActSheet->setCellValue('O2','参与/招募人数');
						$objActSheet->setCellValue('P2','项目状态');
						$objActSheet->setCellValue('Q2','审批状态');
						$objActSheet->setCellValue('R2','添加时间');
						
					    $objStyleA1 = $objActSheet->getStyle('A2:R2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);
						$objActSheet->getColumnDimension('I')->setWidth(10);
						$objActSheet->getColumnDimension('J')->setWidth(15);
						$objActSheet->getColumnDimension('K')->setWidth(20);
						$objActSheet->getColumnDimension('L')->setWidth(10);
						$objActSheet->getColumnDimension('M')->setWidth(10);
						$objActSheet->getColumnDimension('N')->setWidth(10);
						$objActSheet->getColumnDimension('O')->setWidth(10);
						$objActSheet->getColumnDimension('P')->setWidth(10);
						$objActSheet->getColumnDimension('Q')->setWidth(10);
						$objActSheet->getColumnDimension('R')->setWidth(10);
						
					  	$index = 3;
					  	$lists = $project->where($where)->select();
					  	//print_r($lists);die;
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,$v['project_no']);
				    		$objActSheet->setCellValue('B'.$index,$v['title']);
						    $objActSheet->setCellValue('C'.$index,$v['class']);
						    $objActSheet->setCellValue('D'.$index,$v['kehu']);
						    $objActSheet->setCellValue('E'.$index,$v['is_fabu']);

						     $objActSheet->setCellValue('F'.$index,$v['user_name']);//负责人
							$objActSheet->setCellValue('G'.$index,$v['creat_name']);//创建人
							$objActSheet->setCellValue('H'.$index,date('Y-m-d H:i',$v['start_time']));// 招募开始
							$objActSheet->setCellValue('I'.$index,date('Y-m-d H:i',$v['end_time']));//招募结束
							$objActSheet->setCellValue('J'.$index,date('Y-m-d H:i',$v['project_start_time']));//项目开始
							$objActSheet->setCellValue('K'.$index,date('Y-m-d H:i',$v['project_end_time']));//项目结束
							$objActSheet->setCellValue('L'.$index,$v['price']);//感谢金
							$objActSheet->setCellValue('M'.$index,$v['integral']);//积分


							//报名次数，报名成功次数  参与次数 招募
								$baoming=$member_enrol->where("project_id=$v[id]")->count();//报名人数
								$baoming_success=$member_enrol->where("project_id=$v[id] AND baoming=1")->count();//通过
								$canyu=$member_enrol->where("project_id=$v[id] AND baoming=1 AND enrol_start_time >0 ")->count();
							

						    $objActSheet->setCellValue('N'.$index,$baoming_success.'/'.$baoming);//通过/报名人数
						    $objActSheet->setCellValue('O'.$index,$canyu.'/'.$v['demand_num']);//参与次数/招募
							$objActSheet->setCellValue('P'.$index,$v['state']);
							if($v['project_status']=='1'){
								$v['project_status']='审批通过';
							}else{
								$v['project_status']='待审批';
							}
							 $objActSheet->setCellValue('Q'.$index,$v['project_status']);
							  $objActSheet->setCellValue('R'.$index,date('Y-m-d H:i',$v['add_time']));
							// if($nindex!=$index)
							// {
							// 	$index = $nindex;
							// }
							// else
							// {
							// 	WHILE($ARR){

							// 		$index++;
							// 	}
								$index++;
							// }
							

					  	}
			    		break;

			case "member_enrol":
			    	//筛选条件
			    	$file_name="项目报名导出";
			    	$where['project_id']=$_GET['project_id'];
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);			    	
			    	$keyword=trim($_GET['keyword']);
			    	//项目编号
			    	if(trim($_GET['state']))	
				    $where['state']=$_GET['state'];
				    	
			    	if($_GET['sex'])
			    	$where['sex']=trim($_REQUEST['sex']);
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where["a.add_time"] = array(array('gt',strtotime($_REQUEST['start_time'])),array('lt',strtotime($_REQUEST['end_time'])));
			    
			    	$project=M('project');
			    	$member=M('member');
			    	$order=M('order');
			    	$member_enrol=M('member_enrol');
			    		$objActSheet->setTitle('优试项目'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"项目数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','报名时间');
			    		$objActSheet->setCellValue('B2','姓名');
					    $objActSheet->setCellValue('C2','性别');
					    $objActSheet->setCellValue('D2','年龄');
					    $objActSheet->setCellValue('E2','电话');
					    $objActSheet->setCellValue('F2','地区');
					    $objActSheet->setCellValue('G2','开始日期');
					    $objActSheet->setCellValue('H2','结束日期');
						$objActSheet->setCellValue('I2','状态');
						$objActSheet->setCellValue('J2','收货人');
						$objActSheet->setCellValue('K2','收货电话');
						$objActSheet->setCellValue('L2','收货地址');
						$objActSheet->setCellValue('M2','快递');
						$objActSheet->setCellValue('N2','快递单号');
						
						
					    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);
						$objActSheet->getColumnDimension('I')->setWidth(10);
						$objActSheet->getColumnDimension('J')->setWidth(15);
						$objActSheet->getColumnDimension('K')->setWidth(20);
						$objActSheet->getColumnDimension('L')->setWidth(10);
						$objActSheet->getColumnDimension('M')->setWidth(10);
						$objActSheet->getColumnDimension('N')->setWidth(10);
						
					  	$index = 3;
					  	$join = C('DB_PREFIX').'member as b on a.member_id =b.member_id';
					  	// $lists = $member_enrol->join("v_member ON v_member.member_id=v_member_enrol.member_id")->where($where)->select();
					  	$lists = $member_enrol->field('a.*,b.name,b.sex,b.birthday,b.mobile,b.area_name,b.member_id')->alias("a")->join($join)->where($where)->order('a.enrol_id desc')->select();
					  	//print_r($lists);die;
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,date('Y-m-d H:i',$v['add_time']));
					  		$member_info=$member->field('new_area_name,mobile,sex,birthday,name')->where("member_id=$v[member_id]")->find();
					  		$order_info=$order->field('kuaidi,kuaidi_no,name,phone,address')->where("member_id=$v[member_id] AND project_id=$v[project_id]")->find();
					  		$age=birthday_age(date("Y-m-d",$member_info['birthday']));
					  		if(!$v['member_name'])
					  		{
					  			$name=$member_info['name'];
					  		}else{
					  			$name=$v['member_name'];
					  		}
				    		$objActSheet->setCellValue('B'.$index,$name);
						    $objActSheet->setCellValue('C'.$index,$member_info['sex']);
						    $objActSheet->setCellValue('D'.$index,$age);
						    $objActSheet->setCellValue('E'.$index,$member_info['mobile']);

						     $objActSheet->setCellValue('F'.$index,$member_info['new_area_name']);//地区
							$objActSheet->setCellValue('G'.$index,date('Y-m-d H:i',$v['enrol_start_time']));//开始时间
							$objActSheet->setCellValue('H'.$index,date('Y-m-d H:i',$v['enrol_end_time']));// 结束时间
							$objActSheet->setCellValue('I'.$index,$v['state']);//状态
							$objActSheet->setCellValue('J'.$index,$order_info['name']);//项目开始
							$objActSheet->setCellValue('K'.$index,$order_info['phone']);//项目结束
							$objActSheet->setCellValue('L'.$index,$order_info['address']);//感谢金
							$objActSheet->setCellValue('M'.$index,$order_info['kuaidi']);//积分

						    $objActSheet->setCellValue('N'.$index,$order_info['kuaidi_no']);//通过/报名人数
						   
								$index++;
						
							

					  	}
			    		break;

			   case "zhenbie":
			    	//筛选条件
			    	//导出项目 进行中，完成，中止
			    	// $arr=array('项目进行中','已完成','项目中止' );
			    //	$where['state']=array('in','项目进行中,已完成,项目中止');
			    	$file_name="甄别问卷导出";
			    	$where['project_id']=$_GET['project_id'];
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);			    	
			    	$keyword=trim($_GET['keyword']);
			    	//项目编号
			    	if(trim($_GET['state']))	
				    $where['state']=$_GET['state'];
				    	
			    	if($_GET['sex'])
			    	$where['sex']=trim($_REQUEST['sex']);
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where["add_time"] = array(array('gt',strtotime($_REQUEST['start_time'])),array('lt',strtotime($_REQUEST['end_time'])));

			    	
			    	if($_GET['ids']&&$_GET['ids']!='false')
			    	{
			    		$ids=trim($_GET['ids'],',');
			    		$where['enrol_id']=array('in',$ids);
			    	}

			   		 $member=M('member');
			   		 $order=M('order');
			    	$member_ques=M('member_ques');
			    	$ques=M('ques');
			    	$member_enrol=M('member_enrol');
			    	$zimu=array('1'=>'A','2'=>'B','3'=>'C','4'=>'D','5'=>'E','6'=>'F','7'=>'G','8'=>'H','9'=>'I','10'=>'J','11'=>'K','12'=>'L','13'=>'M'
			    		,'14'=>'N','15'=>'O','16'=>'P','17'=>'Q','18'=>'R','19'=>'S','20'=>'T','21'=>'U','22'=>'V','23'=>'W'
			    		,'24'=>'X','25'=>'Y','26'=>'Z');
			    		$objActSheet->setTitle('优试项目甄别问卷'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"甄别问卷数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $ques_list=$ques->field('name')->where("project_id=$_GET[project_id] AND type=1")->order("ques_id desc")->select();
					    foreach($ques_list as $k=>$v)
					    {
					    	$key=$zimu[$k+2].'2';

					    	$objActSheet->setCellValue($key,$v['name']);
					    }
			   
						
						
					 //    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					 //    $objFontA1 = $objStyleA1->getFont();
					 //    $objFontA1->setSize(13); 
					 //    $objFontA1->setBold(true); 
					 //    $objFontA1 = $objStyleA1->getAlignment(); 
					 //    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					 //    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					 //    $objActSheet->getColumnDimension('A')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('B')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('C')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('D')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('E')->setWidth(30);
					 //  	$objActSheet->getColumnDimension('F')->setWidth(15);
					 //  	$objActSheet->getColumnDimension('G')->setWidth(15);
					 //  	$objActSheet->getColumnDimension('H')->setWidth(10);
						// $objActSheet->getColumnDimension('I')->setWidth(10);
						// $objActSheet->getColumnDimension('J')->setWidth(15);
						// $objActSheet->getColumnDimension('K')->setWidth(20);
						// $objActSheet->getColumnDimension('L')->setWidth(10);
						// $objActSheet->getColumnDimension('M')->setWidth(10);
						// $objActSheet->getColumnDimension('N')->setWidth(10);
						
					  	$index = 3;
					  	
					  	$lists=$member_enrol->where($where)->order('member_id desc')->select();
					  	
					  	$nindex = $index;
					  	// print_r($where);die;
					  	foreach($lists as $k=>$v){

					  		$member_info=$member->field('name')->where("member_id=$v[member_id]")->find();
					  		$objActSheet->setCellValue('A'.$index,$member_info['name']);
					  		$ques_info=$member_ques->where("project_id=$v[project_id] and type=1 and member_id=$v[member_id]")->find();
					  		$paper_desc=json_decode($ques_info['paper_desc'],true);
					  		krsort($paper_desc);
					  		$paper_desc=array_values($paper_desc);
					  		// print_r($paper_desc);die;
					  		foreach($paper_desc as $ke=>$vv)
					  		{
					  			$key=$ke+2;
					  			$kk=$zimu[$key];
					  			$objActSheet->setCellValue($kk.$index,$vv['ques_daan']);
					  				
					  		}
				  
						   
								$index++;

					  	}
			    		break;	

			case "fankui":
			    	//筛选条件
			    	$file_name="反馈问卷导出";
			    	$where['state']=array('in','项目进行中,已完成,项目中止,审核中');
			    	$where['project_id']=$_GET['project_id'];
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);			    	
			    	$keyword=trim($_GET['keyword']);
			    	//项目编号
			    	if(trim($_GET['state']))	
				    $where['state']=$_GET['state'];
				    	
			    	if($_GET['sex'])
			    	$where['sex']=trim($_REQUEST['sex']);
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where["add_time"] = array(array('gt',strtotime($_REQUEST['start_time'])),array('lt',strtotime($_REQUEST['end_time'])));
			   		 $member=M('member');
			   		 $order=M('order');
			    	$member_ques=M('member_ques');
			    	$ques=M('ques');
			    	$member_enrol=M('member_enrol');


			    	if($_GET['ids']&&$_GET['ids']!='false')
			    	{
			    		// print_r($_GET['ids']);die;
			    		$ids=trim($_GET['ids'],',');
			    		$where['enrol_id']=array('in',$ids);
			    	}

			    	

			    	$zimu=array('1'=>'A','2'=>'B','3'=>'C','4'=>'D','5'=>'E','6'=>'F','7'=>'G','8'=>'H','9'=>'I','10'=>'J','11'=>'K','12'=>'L','13'=>'M'
			    		,'14'=>'N','15'=>'O','16'=>'P','17'=>'Q','18'=>'R','19'=>'S','20'=>'T','21'=>'U','22'=>'V','23'=>'W'
			    		,'24'=>'X','25'=>'Y','26'=>'Z');
			    		$objActSheet->setTitle('优试项目反馈问卷'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"反馈问卷数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $ques_list=$ques->field('ques_id,name')->where("project_id=$_GET[project_id] AND type=4 ")->order("num asc ,sort asc")->select();
					    foreach($ques_list as $k=>$v)
					    {
					    	$key=$zimu[$k+2].'2';

					    	if($k+2>26&&$k+2<=52)
					    	{	$kk=($k+2)%26;
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		
					    		$objActSheet->setCellValue('A'.$key,$v['ques_id'].$v['name']);
					    	}elseif($k+2>52&&$k+2<=78)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('B'.$key,$v['ques_id'].$v['name']);
					    	}
					    	elseif($k+2>78&&$k+2<=104)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('C'.$key,$v['ques_id'].$v['name']);
					    	}
					    	elseif($k+2>104&&$k+2<=130)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('D'.$key,$v['ques_id'].$v['name']);
					    	}
					    	elseif($k+2>130&&$k+2<=156)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('E'.$key,$v['ques_id'].$v['name']);
					    	}
					    	elseif($k+2>156&&$k+2<=182)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('F'.$key,$v['ques_id'].$v['name']);
					    	}
					    	elseif($k+2>182&&$k+2<=208)
					    	{
					    		$kk=($k+2)%26;
					    		
					    		if($kk=='0')
					    		{
					    			$key='Z2';
					    		}else{
					    			$key=$zimu[$kk].'2';
					    		}
					    		$objActSheet->setCellValue('G'.$key,$v['ques_id'].$v['name']);
					    	}elseif($k+2<=26){
					    	
					    		$objActSheet->setCellValue($key,$v['ques_id'].$v['name']);
					    	}
					    	
					    }
			   
						
						
					    // $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    // $objFontA1 = $objStyleA1->getFont();
					 //    $objFontA1->setSize(13); 
					 //    $objFontA1->setBold(true); 
					 //    $objFontA1 = $objStyleA1->getAlignment(); 
					 //    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					 //    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					 //    $objActSheet->getColumnDimension('A')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('B')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('C')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('D')->setWidth(10);
					 //  	$objActSheet->getColumnDimension('E')->setWidth(30);
					 //  	$objActSheet->getColumnDimension('F')->setWidth(15);
					 //  	$objActSheet->getColumnDimension('G')->setWidth(15);
					 //  	$objActSheet->getColumnDimension('H')->setWidth(10);
						// $objActSheet->getColumnDimension('I')->setWidth(10);
						// $objActSheet->getColumnDimension('J')->setWidth(15);
						// $objActSheet->getColumnDimension('K')->setWidth(20);
						// $objActSheet->getColumnDimension('L')->setWidth(10);
						// $objActSheet->getColumnDimension('M')->setWidth(10);
						// $objActSheet->getColumnDimension('N')->setWidth(10);
						
					  	$index = 3;
					  	$lists=$member_enrol->where($where)->order('member_id desc')->select();
					  // print_r($where);die;
					  	$nindex = $index;
					  	// print_r(json_decode($lists[0]['paper_desc'],true));die;
					  	 $ques_list=$ques->field('ques_id')->where("project_id=$_GET[project_id] AND type=4 ")->order("num asc ,sort asc")->select();
					  	foreach($lists as $kee=>$v){
					  		$paper_desc_list=array();
					  		$member_info=$member->field('name')->where("member_id=$v[member_id]")->find();
					  		$objActSheet->setCellValue('A'.$index,$member_info['name']);
					  		$ques_info=$member_ques->where("project_id=$v[project_id] and type=4 and member_id=$v[member_id]")->find();
					  		$paper_desc=json_decode($ques_info['paper_desc'],true);
					  		
					  		krsort($paper_desc);
					  		$paper_desc=array_values($paper_desc);
					  		// print_r($paper_desc);
					  		 foreach($ques_list as $kkk=>$vkk)
					  		 {
					  		 	foreach($paper_desc as $kkey=>$val)
					  		 	{
					  		 		if($vkk['ques_id']==$val['ques_id'])
					  		 		{
					  		 			$paper_desc_list[]=$val;
					  		 		}
					  		 	}
					  		 }
					  		 // echo"<pre>";
					  		 // print_r($paper_desc);
					  		 // print_r($paper_desc_list);die;
					  		
					  		foreach($paper_desc_list as $k=>$vv)
					  		{
					  			$key=$k+2;
					  			$kka=$zimu[$key];
							  		if($k+2>26&&$k+2<=52)
							    	{	$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('A'.$key.$index,$vv['ques_daan']);
							    	}elseif($k+2>52&&$k+2<=78)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('B'.$key.$index,$vv['ques_daan']);
							    	}
							    	elseif($k+2>78&&$k+2<=104)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('C'.$key.$index,$vv['ques_daan']);
							    	}
							    	elseif($k+2>104&&$k+2<=130)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('D'.$key.$index,$vv['ques_daan']);
							    	}
							    	elseif($k+2>130&&$k+2<=156)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('E'.$key.$index,$vv['ques_daan']);
							    	}
							    	elseif($k+2>156&&$k+2<=182)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('F'.$key.$index,$vv['ques_daan']);
							    	}
							    	elseif($k+2>182&&$k+2<=208)
							    	{
							    		$kk=($k+2)%26;
							    		if($kk=='0')
							    		{
							    			$key='Z';
							    		}else{
							    			$key=$zimu[$kk];
							    		}
							    		$objActSheet->setCellValue('G'.$key.$index,$vv['ques_daan']);
							    	}elseif($k+2<=26){
							    	
							    		$objActSheet->setCellValue($kka.$index,$vv['ques_daan']);
							    	}
					  				
					  		}
				  
						   
								$index++;

					  	}
			    		break;	

			    /*流程状态导出*/
			  case "liucheng":
			    	//筛选条件

			   		$member=M('member');
			    	$member_process=M('member_process');
			    	$project_process=M('project_process');
			    	$member_enrol=M('member_enrol');
			    	$file_name="流程状态导出";
			    	$where['project_id']=$_GET['project_id'];
			    	$time_type=trim($_GET['time_type']);
			    	$start_time=strtotime($_GET['start_time']);
			    	$end_time=strtotime($_GET['end_time']);			    	
			    	$keyword=trim($_GET['keyword']);
			    	//项目编号
			    	if(trim($_GET['state']))	
				    $where['state']=$_GET['state'];
				    	
			    	if($_GET['sex'])
			    	$where['sex']=trim($_REQUEST['sex']);
			    	if($_GET['time_type']&&$start_time)
			    	$where[$time_type]=array('gt',$end_time);
			   		 if($_GET['time_type']&&$end_time)
			    	$where[$time_type]=array('lt',$end_time);
			    	if($_GET['time_type']&&$start_time&&$end_time)
			    	$where["add_time"] = array(array('gt',strtotime($_REQUEST['start_time'])),array('lt',strtotime($_REQUEST['end_time'])));

			    	if($_GET['ids']&&$_GET['ids']!='false')
			    	{
			    		$ids=trim($_GET['ids'],',');
			    		$where['enrol_id']=array('in',$ids);
			    	}


			    	$zimu=array('1'=>'A','2'=>'B','3'=>'C','4'=>'D','5'=>'E','6'=>'F','7'=>'G','8'=>'H','9'=>'I','10'=>'J','11'=>'K','12'=>'L','13'=>'M'
			    		,'14'=>'N','15'=>'O','16'=>'P','17'=>'Q','18'=>'R','19'=>'S','20'=>'T','21'=>'U','22'=>'V','23'=>'W'
			    		,'24'=>'X','25'=>'Y','26'=>'Z');
			    		$objActSheet->setTitle('优试项目流程状态'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"流程状态导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $process_list=$project_process->where("project_id=$_GET[project_id] ")->order("type asc,process_id asc")->select();
					    // print_r($process_list);die;
					  	$sql="select count(process_id) as num,type from v_project_process where project_id=$_GET[project_id]  group by type order by type asc";
					    $inin=$project_process->query($sql);
					    $start_num=1;
					    $end_num=0;

					    foreach($inin as $ke=>$ve)
					    {
					    	$num=$ve['num'];
					    	$end_num=$start_num+$num;
					    	$objActSheet->setCellValue($zimu[$start_num+3].'2','第'.$ve['type'].'天'); 
			    			 // $objActSheet->mergeCells($zimu[$start_num+3].'2:'.$zimu[$start_num+3+$num].'2');
			    			$start_num=$end_num;
			    			
					    }
					     $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    foreach($process_list as $k=>$v)
					    {

					    		$objActSheet->setCellValue('A3','姓名');
					    		$objActSheet->setCellValue('B3','手机号');
					    		$objActSheet->setCellValue('C3','开始时间');
					    		$key=$zimu[$k+4].'3';

					    	$objActSheet->setCellValue($key,$v['name']);

					    }

					    $objStyleA1 = $objActSheet->getStyle('A3:N3');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);
						$objActSheet->getColumnDimension('I')->setWidth(10);
						$objActSheet->getColumnDimension('J')->setWidth(15);
						$objActSheet->getColumnDimension('K')->setWidth(20);
						$objActSheet->getColumnDimension('L')->setWidth(10);
						$objActSheet->getColumnDimension('M')->setWidth(10);
						$objActSheet->getColumnDimension('N')->setWidth(10);
						
					  	$index = 4;
					  	
					  	$lists=$member_enrol->where($where)->order('member_id desc')->select();
					  	
					  	$nindex = $index;
					  	// print_r($where);die;
					  	foreach($lists as $k=>$v){

					  		$member_info=$member->where("member_id=$v[member_id]")->find();
					  		$enrol_info=$member_enrol->where("project_id=$v[project_id] and member_id=$v[member_id]")->find();
					  		$objActSheet->setCellValue('A'.$index,$member_info['name']);
					  		$objActSheet->setCellValue('B'.$index,$member_info['mobile']);
					  		$objActSheet->setCellValue('C'.$index,$enrol_info['enrol_start_time']);
					  		$info=$member_process->where("project_id=$v[project_id] and  member_id=$v[member_id]")->find();
					  		$paper_desc=json_decode($info['process_desc'],true);
					  		krsort($paper_desc);
					  		// $paper_desc=array_values($paper_desc);
					  		// print_r($paper_desc);die;
					  		$i=4;
					  		foreach($paper_desc as $ke=>$vv)
					  		{
					  			
					  			$kk=$zimu[$i];
					  			
					  			$objActSheet->setCellValue($kk.$index,'已完成');
					  				$i++;
					  		}

								$index++;

					  	}
			    		break;			


			    case "goods":
			    	//筛选条件
			    	$file_name="商品导出";	    	
			    	$keyword=trim($_GET['keyword']);
			    	$type_id=trim($_GET['type_id']);
			    	if($keyword)
			    	{
			    		$where['goods_name']=array('like','%'.$keyword.'%');
			    	}
			    	if($type_id)
			    	{
			    		$where['type_id']=$type_id;
			    	}
			    
			    	$goods=M('goods');

			    		$objActSheet->setTitle('优试项目'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"商品数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','商品名');
			    		$objActSheet->setCellValue('B2','商品分类');
					    $objActSheet->setCellValue('C2','商品价格');
					    $objActSheet->setCellValue('D2','商品规格');
					    $objActSheet->setCellValue('E2','所需积分');
					    $objActSheet->setCellValue('F2','库存');
					    $objActSheet->setCellValue('G2','兑换比例');
					    $objActSheet->setCellValue('H2','添加时间');
					
						
						
					    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);

						
					  	$index = 3;
					  
					  	$lists = $goods->where($where)->order('goods_id desc')->select();
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,$v['goods_name']);
					  		if($v[type_id])
					  		{
					  			$type_info=$type->field('type_name')->where("type_id=$v[type_id]")->find();
					  			$name=$type_info['type_name'];
					  		}else{
					  			$name="暂无";
					  		}
				    		$objActSheet->setCellValue('B'.$index,$name);
						    $objActSheet->setCellValue('C'.$index,$v['price']);
						    $objActSheet->setCellValue('D'.$index,$v['guige']);
						    $objActSheet->setCellValue('E'.$index,$v['jifen']);
						     $objActSheet->setCellValue('F'.$index,$v['num']);//地区
							$objActSheet->setCellValue('G'.$index,$v['bili']);//开始时间
							$objActSheet->setCellValue('H'.$index,date('Y-m-d H:i',$v['add_time']));// 结束时间

								$index++;
	
					  	}
			    		break;

			    case "order":
			    	//筛选条件
			    	$file_name="积分兑换订单导出";
			    	$search_type=trim($_GET['search_type']);
			    	$keyword=trim($_GET['keyword']);
			    	$state=trim($_GET['state']);

			    	if($keyword){
			    		//订单编号
			    		if($search_type=='1')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['order_no']=array('like',$word);
				    	}
			    		//用户名
				    	if($search_type=='2')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['user_name']=array('like',$word);
				    	}
			    		//商品名
				    	if($search_type=='3')
				    	{	
				    		$word="%".$keyword."%";
				    		$where['goods_name']=array('like',$word);
				    		
				    	}
				    	//收货电话
				    	if($search_type=='4')
				    	{	
				    		$word=$keyword."%";
				    		$where['phone']=array('like',$word);
				    	}				    	
			    	}
			    	if($state)
			    	{
			    		$where['state']=$state;
			    	}
			    
			    	$jifen_order=M('jifen_order');

			    		$objActSheet->setTitle('优试项目'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"商品数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','订单编号');
			    		$objActSheet->setCellValue('B2','用户名');
					    $objActSheet->setCellValue('C2','商品名');
					    $objActSheet->setCellValue('D2','兑换数量');
					    $objActSheet->setCellValue('E2','所需积分');
					    $objActSheet->setCellValue('F2','收货人姓名');
					    $objActSheet->setCellValue('G2','收货人电话');
					    $objActSheet->setCellValue('H2','详细地址');
					    $objActSheet->setCellValue('I2','快递');
					    $objActSheet->setCellValue('J2','快递编号');
					    $objActSheet->setCellValue('J2','兑换时间');					    
					
						
						
					    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(30);
					  	$objActSheet->getColumnDimension('I')->setWidth(15);
					  	$objActSheet->getColumnDimension('J')->setWidth(10);
						$objActSheet->getColumnDimension('K')->setWidth(10);
					  	$index = 3;
					  
					  	$lists = $jifen_order->where($where)->order('goods_id desc')->select();
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,' '.$v['order_no']);
					  		
				    		$objActSheet->setCellValue('B'.$index,$v['user_name']);
						    $objActSheet->setCellValue('C'.$index,$v['goods_name']);
						    $objActSheet->setCellValue('D'.$index,$v['num']);
						    $objActSheet->setCellValue('E'.$index,$v['jifen']);
						     $objActSheet->setCellValue('F'.$index,$v['name']);//收货人
							$objActSheet->setCellValue('G'.$index,' '.$v['phone']);//收货电话
							$objActSheet->setCellValue('H'.$index,$v['address']);// 收货地址
							$objActSheet->setCellValue('I'.$index,$v['kuaidi']);// 快递
							$objActSheet->setCellValue('J'.$index,' '.$v['kuaidi_no']);// 快递编号
							$objActSheet->setCellValue('K'.$index,date("Y-m-d",$v['add_time']));// 兑换时间
							//$objActSheet->setCellValue('J'.$index,date("Y-m-d",$v['fa_time']));// 快递编号


								$index++;
	
					  	}
			    		break;

			    case "goods":
			    	//筛选条件
			    	$file_name="商品导出";	    	
			    	$keyword=trim($_GET['keyword']);
			    	$type_id=trim($_GET['type_id']);
			    	if($keyword)
			    	{
			    		$where['goods_name']=array('like','%'.$keyword.'%');
			    	}
			    	if($type_id)
			    	{
			    		$where['type_id']=$type_id;
			    	}
			    
			    	$goods=M('goods');

			    		$objActSheet->setTitle('优试项目'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"商品数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','商品名');
			    		$objActSheet->setCellValue('B2','商品分类');
					    $objActSheet->setCellValue('C2','商品价格');
					    $objActSheet->setCellValue('D2','商品规格');
					    $objActSheet->setCellValue('E2','所需积分');
					    $objActSheet->setCellValue('F2','库存');
					    $objActSheet->setCellValue('G2','兑换比例');
					    $objActSheet->setCellValue('H2','添加时间');
					
						
						
					    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);

						
					  	$index = 3;
					  
					  	$lists = $goods->where($where)->order('goods_id desc')->select();
					  	$nindex = $index;
					  	foreach($lists as $k=>$v){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,$v['goods_name']);
					  		if($v[type_id])
					  		{
					  			$type_info=$type->field('type_name')->where("type_id=$v[type_id]")->find();
					  			$name=$type_info['type_name'];
					  		}else{
					  			$name="暂无";
					  		}
				    		$objActSheet->setCellValue('B'.$index,$name);
						    $objActSheet->setCellValue('C'.$index,$v['price']);
						    $objActSheet->setCellValue('D'.$index,$v['guige']);
						    $objActSheet->setCellValue('E'.$index,$v['jifen']);
						     $objActSheet->setCellValue('F'.$index,$v['num']);//地区
							$objActSheet->setCellValue('G'.$index,$v['bili']);//开始时间
							$objActSheet->setCellValue('H'.$index,date('Y-m-d H:i',$v['add_time']));// 结束时间

								$index++;
	
					  	}
			    		break;

			    	case "airradio":
			    	//筛选条件
			    	$file_name="环境监测仪数据导出";	    	
			    	$project_id=trim($_GET['project_id']);
			    	//enrol_id
			    	$ids=trim($_GET['ids']);	
			    	$enrol=explode(',',$ids);
			    	// print_r($enrol);die;
			    	$member_enrol=M('member_enrol');
			    	$enrol_info=$member_enrol->where("enrol_id=$enrol[0]")->find();

			    		$objActSheet->setTitle('环境监测仪数据导出'); //设置当前活动sheet的名称
			    		$objActSheet->setCellValue('A1',"环境监测仪数据导出"); 
			    		$objActSheet->mergeCells('A1:N1');
			    		$objStyleA1 = $objActSheet->getStyle('A1');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(15); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
			    		$objActSheet->setCellValue('A2','时间');
			    		$objActSheet->setCellValue('B2','pm2.5');
					    $objActSheet->setCellValue('C2','pm10');
					    $objActSheet->setCellValue('D2','温度');
					    $objActSheet->setCellValue('E2','湿度');

					    $objStyleA1 = $objActSheet->getStyle('A2:N2');
					    $objFontA1 = $objStyleA1->getFont();
					    $objFontA1->setSize(13); 
					    $objFontA1->setBold(true); 
					    $objFontA1 = $objStyleA1->getAlignment(); 
					    $objFontA1->setHorizontal($PHPExcel_Style_Alignment::VERTICAL_CENTER); 
					    $objFontA1->setVertical($PHPExcel_Style_Alignment::VERTICAL_CENTER);
					    $objActSheet->getColumnDimension('A')->setWidth(10);
					  	$objActSheet->getColumnDimension('B')->setWidth(10);
					  	$objActSheet->getColumnDimension('C')->setWidth(10);
					  	$objActSheet->getColumnDimension('D')->setWidth(10);
					  	$objActSheet->getColumnDimension('E')->setWidth(30);
					  	$objActSheet->getColumnDimension('F')->setWidth(15);
					  	$objActSheet->getColumnDimension('G')->setWidth(15);
					  	$objActSheet->getColumnDimension('H')->setWidth(10);
					
					  	$index = 3;
					  	$device_id=$enrol_info['device_id'];
						$link=mysql_connect("localhost","phpclient","phppassword"); 
						if(!$link) echo "FAILD!".mysql_error(); 
						mysql_select_db('environment',$link);
						if($device_id)
						{
							$sql="select `temperature`,`humility`,`pm25`,`pm10`,`create_time` from airradio where `device_id`='".$device_id."' order by `utc_time` desc  ";
							$res=mysql_query($sql);
							//$row=mysql_fetch_assoc($res);
						}
						mysql_close($link);
					  	
					  	$nindex = $index;
					  	while($row=mysql_fetch_assoc($res)){
					  		
					  		//$age=birthday_age(date("Y-m-d",$v['birthday']));
					  		$objActSheet->setCellValue('A'.$index,$row['create_time']);
					  		
				    		$objActSheet->setCellValue('B'.$index,$row['pm25']);
						    $objActSheet->setCellValue('C'.$index,$row['pm10']);
						    $objActSheet->setCellValue('D'.$index,$row['temperature']);
						    $objActSheet->setCellValue('E'.$index,$row['humility']);
						     
								$index++;
	
					  	}
			    		break;


			    	}//switch


			   //输出流
			    $outputFileName =$file_name.date('Y-m-d ',time()).".xls"; 
				//到文件 
				////$objWriter->save($outputFileName); 
				//or 
				//到浏览器 
				   
				   header("Content-Type: application/force-download"); 
				   header("Content-Type: application/octet-stream"); 
				   header("Content-Type: application/download"); 
				   header('Content-Disposition:inline;filename="'.$outputFileName.'"'); 
				   header("Content-Transfer-Encoding: binary"); 
				   header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT"); 
				   header("Cache-Control: must-revalidate, post-check=0, pre-check=0"); 
				   header("Pragma: no-cache"); 
				   $objWriter->save('php://output');  	

	}

	
}